[workspace]
resolver = "2"
members = [
    "crates/kicad-ecs",
    "crates/kiforge-common", 
    "crates/kiforge-core",
    "crates/kiforge-ui",
    "crates/kiforge-plugins",
    "crates/kiforge-export",
    "kiforge",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["James Bonanno <atlantix-eda@proton.me>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Atlantix-EDA/KiForge"
homepage = "https://github.com/Atlantix-EDA/KiForge"
documentation = "https://docs.rs/kiforge"
keywords = ["pcb", "gerber", "kicad", "eda", "electronics"]
categories = ["science", "simulation", "visualization"]

[workspace.dependencies]
# Core KiForge dependencies - shared versions across workspace
bevy_ecs = "0.14"
egui = "0.31.1"
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["image"] }
egui_dock = { version = "0.16.0", features = ["serde"] }
egui_lens = "0.1.0"
egui_mobius = "0.3.0-alpha.31"
egui_mobius_reactive = "0.3.0-alpha.31"

# Gerber and graphics
gerber_viewer = "0.2.0"
gerber_types = { package = "gerber-types", version = "0.4.0" }
gerber_parser = "0.2.1"
nalgebra = "0.33"
image = "0.24"

# Async and IPC
tokio = { version = "1", features = ["full"] }
futures = "0.3"
nng = "1.0.1"
protobuf = "3.7.2"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Database and storage
sled = "0.34"

# Logging and error handling
log = "0.4"
env_logger = "0.11.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
thiserror = "1.0"
eyre = "0.6"

# System and platform
dirs = "5.0"
sysinfo = "0.35.1"
local-ip = "0.1.0"
local-ip-address = "0.6.5"
chrono = { version = "0.4.41", features = ["serde"] }
chrono-tz = "0.10"
notify = "8.0.0"

# Utilities
regex = "1.10"
once_cell = "1.19"
rfd = "0.15.3"
num-traits = "0.2.17"
rand = "0.8"

# Plugin system
wasmtime = "27.0"
libloading = "0.8"

# Build dependencies
protobuf-codegen = "3.7.2"
walkdir = "2.4.0"

# Development dependencies (for examples and tests)
prettytable-rs = "0.10"

# Workspace crates (defined as path dependencies)
kicad-ecs = { path = "crates/kicad-ecs" }
kiforge-common = { path = "crates/kiforge-common" }
kiforge-core = { path = "crates/kiforge-core" }
kiforge-ui = { path = "crates/kiforge-ui" }
kiforge-plugins = { path = "crates/kiforge-plugins" }
kiforge-export = { path = "crates/kiforge-export" }